database=postgres
db.project = ${POSTGRES_DB_PROJECT}
db.server = ${POSTGRES_DB_SERVER}
db.name = ${POSTGRES_DB_NAME}
db.user = ${POSTGRES_DB_USER}
db.pw = ${POSTGRES_DB_PASS}
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql:///${db.name}?cloudSqlInstance=${db.project}:us-central1:${db.server}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${db.user}&password=${db.pw}&useSSL=false}
